### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by annietupek**
This creates a Jenkins file for us to build and test OSCC and all its branches in Jenkins.

### CODE REVIEW

**Comment by jeffweiss** [comment]
We paired on this. As one can see from the wonderful green check next to each commit, these commits built successfully in Jenkins.

**Comment by evanlivingston** [comment]
It currently looks like the jenkinsfile calls out the target vehicle explicitly ('kia_soul_ps'), is it possible to make this more generalized to build future makes of vehicles without specifically calling them out.

**Comment by jeffweiss** [comment]
@evanlivingston Yes. That seems like something we should definitely do, but at the time we add a second vehicle. If that's imminent within the next couple weeks, then I concur, we should definitely do it now. If it's beyond that, then I'm reluctant to add complexity for no immediate value.

**Comment by evanlivingston** [comment]
Great, sounds good to me!

**Pull request merged**
