### PR TITLE
Modified System diagram

### PR DESCRIPTION
**Pull request by cotos**
Added the connectors we are using, changed CAN gateway to use DB9 connector.

### CODE REVIEW

**Comment by evanlivingston** [comment]
The DB-9 is shown on the Control CAN (red & blue wires) where it connects into the gateway module, but this is inaccurate. DB-9s are only used on the Control CAN bus on the ECU side and on the premade OBD-II to DB-9 cable.

**Comment by LucasBuckland** [comment]
There should be a two pin connector to the brake module for power.

**Comment by ltbj** [comment]
@cotos you have the approvals you need but there's a merge conflict that needs resolved.

**Comment by cotos** [comment]
Unfortunately I do not have write access to this repository so I cannot resolve the conflict

**Pull request merged**
